# Setup antigen base directory
ZSHA_BASE=$HOME/sources/dotfiles/zsh

# source /home/tonio/.local/bin/virtualenvwrapper.sh
PATH=$PATH:~/.local/bin:~/.node/bin

# Load antigen
source $ZSHA_BASE/antigen.zsh

# Load the oh-my-zsh's library
antigen use oh-my-zsh

antigen bundle git
antigen bundle git-flow
antigen bundle virtualenvwrapper

antigen theme agnoster

antigen apply

sudo-command-line() {
    [[ -z $BUFFER ]] && zle up-history
    if [[ $BUFFER == sudo\ * ]]; then
        LBUFFER="${LBUFFER#sudo }"
    elif [[ $BUFFER == $EDITOR\ * ]]; then
        LBUFFER="${LBUFFER#$EDITOR }"
        LBUFFER="sudoedit $LBUFFER"
    elif [[ $BUFFER == sudoedit\ * ]]; then
        LBUFFER="${LBUFFER#sudoedit }"
        LBUFFER="$EDITOR $LBUFFER"
    else
        LBUFFER="sudo $LBUFFER"
    fi
}

 fzf-vim() {
     vim $(~/.fzf/bin/fzf)
 }
zle -N sudo-command-line
# Defined shortcut keys: ss
bindkey "!!" sudo-command-line
bindkey -M vicmd '!!' sudo-command-line

alias f=fzf-vim
alias dps="docker ps"
alias di="docker inspect"
alias dvi="docker volume inspect"
alias dni="docker network inspect"
alias dc="docker-compose"
alias dcs="docker-compose stop"
alias dcu="docker-compose up"
alias dcub="docker-compose up --build"
alias dcud="docker-compose up -d"
alias dcl="docker-compose logs -f"
alias dcp="docker-compose pull"
alias dcr="docker-compose restart"
alias meteo="curl http://wttr.in/Chateauneuf-grasse"
alias vim="nvim"
alias gp="git remote | xargs -L1 git push --all"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

if [[ ! $TERM =~ screen ]]; then
    exec tmux
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true
