# Setup antigen base directory
ZSHA_BASE=$HOME/sources/dotfiles/zsh

PATH=$PATH:~/.local/bin

# Load antigen
source $ZSHA_BASE/antigen.zsh

# Load the oh-my-zsh's library
antigen use oh-my-zsh lib/

antigen bundle git
antigen bundle virtualenvwrapper

antigen bundle dracula/zsh
antigen theme dracula/zsh dracula

antigen apply

sudo-command-line() {
    [[ -z $BUFFER ]] && zle up-history
    if [[ $BUFFER == sudo\ * ]]; then
        LBUFFER="${LBUFFER#sudo }"
    elif [[ $BUFFER == $EDITOR\ * ]]; then
        LBUFFER="${LBUFFER#$EDITOR }"
        LBUFFER="sudoedit $LBUFFER"
    elif [[ $BUFFER == sudoedit\ * ]]; then
        LBUFFER="${LBUFFER#sudoedit }"
        LBUFFER="$EDITOR $LBUFFER"
    else
        LBUFFER="sudo $LBUFFER"
    fi
}

bindkey -s '^v' 'nvim $(fzf)^M'
bindkey '^f' fzf-cd-widget
zle -N sudo-command-line
# Defined shortcut keys: ss
bindkey "!!" sudo-command-line
bindkey -M vicmd '!!' sudo-command-line

cdl() { cd "$@" && ls; }

alias dps="docker ps"
alias di="docker inspect"
alias dvi="docker volume inspect"
alias dni="docker network inspect"
alias dc="docker-compose"
alias dcs="docker-compose stop"
alias dcu="docker-compose up"
alias dcd="docker-compose down"
alias dcub="docker-compose up --build"
alias dcud="docker-compose up -d"
alias dcl="docker-compose logs -f"
alias dcp="docker-compose pull"
alias dcr="docker-compose restart"
alias meteo="curl http://wttr.in/Chateauneuf-grasse"
alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias rg="rgrep -n"
alias gv="grep -v"
alias gp="git remote | xargs -L1 git push --all"

if [[ ! $TERM =~ screen ]]; then
    exec tmux
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
alias lg='lazygit'
export PATH="/home/antoine/.local/share/solana/install/active_release/bin:$PATH"
#export PATH="$HOME/.cargo/bin:$PATH"
#. $HOME/.cargo/env

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Deactivate ctrl-s for vim
if [[ -t 0 && $- = *i* ]]
then
    stty -ixon
fi

export PATH="$PATH:/home/antoine/.starklings/dist/starklings"

export PATH="$PATH:/home/antoine/.protostar/dist/protostar"

export PATH="$HOME/.poetry/bin:$PATH"

export PATH="$PATH:/usr/local/go/bin"

export PATH="$PATH:$HOME/.local/bin"

export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"
